### ISSUE TITLE
Hitting WDT resets with ESP8266

### ISSUE THREAD

**Issue by caternuson** [adafruit/Adafruit_MLX90640#2]
Discovered while attempting to troubleshoot this thread:
https://forums.adafruit.com/viewtopic.php?f=19&t=185356

Seems like some kind of memory clobbering issue preventing the Arduino `loop()` from successfully looping and eventually hitting a WDT reset. Here is a simple sketch to demonstrate. Note it doesn't do anything other than call `begin()` on the MLX90640 instance.

```cpp
#include <Adafruit_MLX90640.h>

Adafruit_MLX90640 mlx;
int count = 0;

void setup() {
  Serial.begin(115200);
  while (!Serial) delay(10);

  Serial.println("Adafruit MLX90640 Test");
  
  if (!mlx.begin()) {
    Serial.println("MLX90640 not found!");
    while (1) delay(10);
  }
  Serial.println("Found Adafruit MLX90640");
}

void loop() {
  Serial.print("count = "); Serial.println(count++);
  Serial.flush();
  delay(500);
}
```

Running that sketch on a Feather ESP8266 results in:
![Screenshot from 2021-12-13 09-37-09](https://user-images.githubusercontent.com/8755041/145861493-d480d98b-1de7-4e08-9e27-706f3fee6a7e.png)

Simply comment out the call to `begin()`, and sketch runs as expected.
![Screenshot from 2021-12-13 09-42-02](https://user-images.githubusercontent.com/8755041/145861715-0c0fbb9e-d146-41e9-8917-37a4a7232078.png)

**Comment by JVaassen** [comment]
I tried to move 3 float arrays of 768 elements from their respective functions  : 
ExtractKtaPixelParameters
ExtractKvPixelParameters
ExtractAlphaParameters

to the front of the file and declared them static. It moves them from stack to heap. After that the demo works on ESP8266..
So the stack crash is solved. Probably setting a stack size param could also help, but didn't investigate yet.

**Comment by sorryusernameisalreadytaken** [comment]
I am in the same boat.

@caternuson can you test this code:
```
#include <Adafruit_MLX90640.h>

Adafruit_MLX90640 mlx;
int count = 0;
static float mlx90640To[768];

void setup() {
  Serial.begin(115200);
  while (!Serial) delay(10);

  Serial.println("Adafruit MLX90640 Test");
  
  if (!mlx.begin()) {
    Serial.println("MLX90640 not found!");
    while (1) delay(10);
  }
  Serial.println("Found Adafruit MLX90640");
}

void loop() {
  Serial.print("count = "); Serial.println(count++);
  Serial.flush();
  
  mlx.getFrameData(mlx90640To);
  mlx.interpolateOutliers(mlx90640To);
  delay(50);
}
```
@JVaassen is this your idea?

**Comment by caternuson** [comment]
@sorryusernameisalreadytaken Which library are you using? These methods are not in this one:
```cpp
  mlx.getFrameData(mlx90640To);
  mlx.interpolateOutliers(mlx90640To);
```

**Comment by caternuson** [comment]
Actually, thanks to @JVaassen 's tip, that helped find the issue. See PR #3 for a nominal fix.

**Comment by sorryusernameisalreadytaken** [comment]
> Actually, thanks to @JVaassen 's tip, that helped find the issue. See PR #3 for a nominal fix.

Can you show me your final sketch? This could help mse a lot.

**Comment by caternuson** [comment]
No change needed to sketch. The fix is to the library code.
